# Generated by Django 3.1.5 on 2021-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helps_received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mechanic_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=50)),
                ('customer_contact_no', models.CharField(max_length=50)),
                ('customer_description', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('customer_latitude', models.CharField(max_length=200)),
                ('customer_longitude', models.CharField(max_length=200)),
                ('avg_rating', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
