# Generated by Django 3.1.5 on 2021-05-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helps_received',
            name='avg_rating',
        ),
    ]
