# Generated by Django 3.1.5 on 2021-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_helps_received_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps_received',
            name='avg_rating',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
