# Generated by Django 3.1.5 on 2021-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helps_finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_feedback_given', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('mechanic_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('customer_contact_no', models.CharField(max_length=100)),
                ('customer_description', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('customer_latitude', models.CharField(max_length=100)),
                ('customer_longitude', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='need_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('contact_no', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
